name = "parkinson-br-counters"
main = "worker.js"
compatibility_date = "2025-04-01"

kv_namespaces = [
  { binding = "COUNTERS", id = "dbdc3054fc6f4049aa1a890880d1dba7" }
]

[vars]
ALLOWED_ORIGINS = "https://leonardochalhoub.github.io,http://localhost:8000"
